project_id = "uqrexrcgzjranthaltrq"

[functions.generate-keywords]
verify_jwt = false

[functions.generate-titles]
verify_jwt = false

[functions.generate-description]
verify_jwt = false

[functions.generate-tags]
verify_jwt = false

[functions.generate-thumbnails]
verify_jwt = false
