project_id = "uqrexrcgzjranthaltrq"

[functions.generate-keywords]
verify_jwt = true

[functions.generate-titles]
verify_jwt = true

[functions.generate-description]
verify_jwt = true

[functions.generate-tags]
verify_jwt = true
